import { Helmet } from "react-helmet-async";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PublicNav } from "@/components/public-nav";
import { PublicFooter } from "@/components/public-footer";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Calendar, ArrowRight } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

type FAQCategory = "compliance" | "technical" | "integration" | "security" | "pricing" | "operations";

const faqCategories: { id: FAQCategory; label: string }[] = [
  { id: "compliance", label: "EU DPP Compliance" },
  { id: "technical", label: "Technical" },
  { id: "integration", label: "SAP & ERP Integration" },
  { id: "security", label: "Security & Data Protection" },
  { id: "pricing", label: "Pricing & Plans" },
  { id: "operations", label: "Operations & Support" },
];

const faqs: Record<FAQCategory, { q: string; a: string }[]> = {
  compliance: [
    {
      q: "What is the EU Digital Product Passport (DPP) regulation?",
      a: "The Digital Product Passport is mandated by the EU Ecodesign for Sustainable Products Regulation (ESPR), Regulation (EU) 2024/1781, adopted on June 27, 2024. It requires that all products sold in the EU carry a standardized digital record accessible via a unique product identifier (typically a QR code or data carrier). This record must contain comprehensive information across seven mandatory categories: product identification, materials and composition, environmental impact, durability and repairability, ownership and lifecycle history, compliance and certifications, and end-of-life instructions. The regulation is part of the EU Green Deal and Circular Economy Action Plan, aiming to make sustainable products the norm in Europe. It replaces the original Ecodesign Directive 2009/125/EC and significantly expands its scope from energy-related products to nearly all physical goods placed on the EU market."
    },
    {
      q: "When does my industry need to comply?",
      a: "The ESPR phased rollout follows a strict timeline: Phase 1 (February 18, 2027) — Industrial and EV batteries must carry Digital Product Passports under the EU Battery Regulation (2023/1542). This is the earliest and most immediate deadline. Phase 2 (2028) — Textiles, consumer electronics, ICT equipment, and iron/steel products must carry DPPs with full material composition, repairability scores, and environmental impact data. Phase 3 (2029) — Furniture, construction materials, chemicals, tires, and detergents require complete lifecycle documentation. Phase 4 (2030) — Universal mandate across all remaining product categories sold in the EU. We strongly recommend beginning compliance preparation 12-18 months before your industry's deadline. For battery manufacturers, this means starting now. The European Commission will publish delegated acts with specific requirements for each product category, and PhotonicTag monitors these publications to ensure our schemas remain current."
    },
    {
      q: "What are the penalties for non-compliance?",
      a: "Non-compliance with ESPR carries significant financial and operational consequences. Each EU member state sets its own enforcement framework, but penalties typically include: (1) Fines of €100,000 or more per product violation, with repeat offenses carrying escalating penalties; (2) Product seizure at EU borders — non-compliant goods may be detained by customs authorities and prevented from entering the single market; (3) Market withdrawal orders requiring companies to recall or remove non-compliant products already in circulation; (4) Public naming — authorities may publish the names of non-compliant companies, causing reputational damage; (5) Supply chain disruption — retailers and distributors are increasingly requiring DPP compliance from suppliers, meaning non-compliance can result in lost contracts and delisting. The regulation follows the precedent set by REACH and CE marking enforcement. Companies that proactively comply gain a competitive advantage as supply chain partners increasingly mandate DPP data from their vendors."
    },
    {
      q: "What data fields are required in a Digital Product Passport?",
      a: "ESPR mandates seven categories of data, each with specific required fields: (1) Product Identification — Global Trade Item Number (GTIN), manufacturer name, model/variant identifier, SKU, batch/serial number, country of origin, manufacturing facility, and date of manufacture. (2) Materials & Composition — Complete bill of materials with percentage breakdown, recycled content percentage, list of hazardous substances (SCIP database alignment), REACH-relevant chemicals, and material sourcing information. (3) Environmental Impact — Product Carbon Footprint (PCF) in kg CO₂e using ISO 14067 methodology, water footprint, energy consumption during manufacture and use, and environmental certifications (EU Ecolabel, Nordic Swan, Blue Angel). (4) Durability & Repairability — EU Repairability Score (1-10), expected product lifespan in hours/cycles/years, spare parts availability period, repair manual accessibility, and warranty duration. (5) Ownership & Lifecycle — Manufacture date, first sale date, ownership transfer history, refurbishment/repair events, and warranty claims. (6) Compliance & Certifications — CE marking declaration, safety certifications (UL, TÜV, etc.), energy efficiency class, RoHS/WEEE compliance, and conflict minerals disclosure (Regulation 2017/821). (7) End-of-Life — Disassembly instructions with time estimates, recyclable material percentage, recycling facility locator, take-back program availability, and proper disposal instructions for hazardous components. PhotonicTag's schema covers all seven categories with additional fields for industry-specific requirements (e.g., battery chemistry, cycle life, state-of-health for batteries; fiber composition and microplastic shedding data for textiles)."
    },
    {
      q: "Does PhotonicTag cover both the Battery Regulation and ESPR?",
      a: "Yes, PhotonicTag fully supports both regulations. The EU Battery Regulation (2023/1542) was the first regulation to mandate digital product passports and has the earliest compliance deadline (February 2027). PhotonicTag's battery-specific DPP schema includes all required fields: battery chemistry and composition, rated capacity (Ah/Wh), cycle life and expected lifetime, state-of-health (SoH) at time of sale, carbon footprint per kWh (calculated using the EU's Product Environmental Footprint methodology), recycled content percentages for cobalt, lithium, nickel, and lead, collection and recycling information, supply chain due diligence (including sourcing of cobalt, lithium, and natural graphite), and QR code linking to the battery passport. The platform simultaneously supports the broader ESPR (2024/1781) requirements for all other product categories, using a shared core schema with industry-specific extensions. This means a single PhotonicTag installation can manage both battery passports and general-purpose DPPs, which is critical for conglomerates operating across multiple product lines."
    },
    {
      q: "How quickly can we achieve compliance?",
      a: "PhotonicTag's typical implementation follows a 4-8 week timeline, depending on your data maturity and integration complexity: Week 1-2: Discovery & Data Audit — We assess your current product data landscape, identify gaps against ESPR requirements, map existing ERP/PLM fields to DPP categories, and define the product scope for the initial rollout. This phase includes a compliance gap analysis that identifies exactly which data fields you're missing. Week 2-3: Integration & Configuration — SAP connector setup (if applicable), field mapping configuration, authentication and access control setup, and environment provisioning. For organizations with well-structured SAP material master data, much of this can be automated. Week 3-4: Data Population & AI — Product data import (via Excel, API, or SAP sync), QR code generation, AI insight generation (sustainability analysis, circularity scoring, repair guides), and consumer-facing scan page deployment. Week 4-5: Validation & Testing — End-to-end compliance verification against ESPR delegated acts, user acceptance testing, performance testing under expected load, and security review. Week 5-6: Go-Live & Training — Production deployment, admin and team training, documentation handover, and establishment of ongoing support procedures. Organizations with clean, well-structured data in SAP S/4HANA can often complete this process in 4 weeks. More complex scenarios involving multiple ERP systems, legacy data migration, or custom integrations may extend to 8 weeks."
    },
    {
      q: "What happens to existing products already in the market?",
      a: "The ESPR requires DPPs for products 'placed on the market' after the relevant deadline. Products already in circulation before the deadline are generally exempt. However, there are important nuances: (1) Products manufactured before the deadline but placed on the market after it are subject to DPP requirements; (2) Spare parts and accessories sold independently may need their own DPPs depending on the product category; (3) Refurbished or remanufactured products re-entering the market may require updated DPPs. PhotonicTag supports retroactive DPP creation for existing product lines, allowing you to build compliance for your entire catalogue even if the initial rollout covers only new products. Our AI-powered data enrichment can help fill gaps in legacy product data using manufacturer specifications and public databases."
    },
    {
      q: "How does PhotonicTag ensure DPP data remains current and valid?",
      a: "Maintaining DPP accuracy over time is a regulatory requirement. PhotonicTag addresses this through: (1) Bidirectional SAP sync that automatically updates DPP data when material master records change; (2) CloudEvents audit trail recording every data modification with timestamps, user identity, and change reason; (3) Version control for DPP records so the full history of changes is preserved; (4) Automated validation rules that flag incomplete or inconsistent data; (5) AI-powered anomaly detection that identifies potential data quality issues; (6) Scheduled compliance checks that verify DPP completeness against the latest regulatory requirements. For battery passports specifically, the platform supports ongoing state-of-health updates from IoT sensors, ensuring the DPP reflects the battery's current condition throughout its lifecycle."
    },
  ],
  technical: [
    {
      q: "What technology stack does PhotonicTag use?",
      a: "PhotonicTag is built on a modern, enterprise-grade cloud-native architecture: Frontend — React 18 with TypeScript and Vite for fast, type-safe development. Shadcn/ui component library (built on Radix UI primitives) for accessible, customizable UI components. TanStack React Query for efficient server state management and caching. Tailwind CSS with custom design tokens for consistent theming. Backend — Node.js 20 LTS with Express for high-performance HTTP handling. TypeScript with ESM modules for type safety across the full stack. RESTful JSON APIs under /api/* prefix with comprehensive input validation using Zod schemas. Database — PostgreSQL (Neon-backed) with Drizzle ORM for type-safe database operations. Schema-first design with automatic Zod validation schema generation. Encrypted session storage via connect-pg-simple. AI — OpenAI GPT-4o integration for sustainability analysis, repair guides, circularity scoring, and risk assessment. Cached inference results for performance and cost efficiency. Security — OAuth 2.0 / OpenID Connect for admin authentication. bcrypt password hashing (cost factor 10) for team/demo authentication. Role-based access control with three-tier permission system. Events — CloudEvents specification-compliant event bus for audit logging, traceability, and decoupled event handling."
    },
    {
      q: "How are QR codes generated and managed?",
      a: "QR codes in PhotonicTag serve as the primary data carrier linking physical products to their Digital Product Passports, as required by ESPR. Technical implementation: QR codes are generated server-side using the 'qrcode' Node.js library with error correction level 'M' (15% redundancy). Each code encodes a unique URL in the format /product/{uuid} that resolves to the product's public DPP page. Codes are stored as high-resolution data URLs (Base64-encoded PNG) directly in the product record for instant retrieval. The public scan page is fully responsive and mobile-optimized, designed for consumers scanning products in-store with their smartphone camera. QR codes are generated automatically during product creation and cannot be remapped to a different product record. The platform supports bulk QR code generation for existing product catalogs and can output QR codes in formats suitable for direct integration into product packaging workflows (SVG, PNG, PDF with crop marks). For advanced use cases, PhotonicTag also supports NFC (Near Field Communication), RFID, and BLE (Bluetooth Low Energy) data carriers through its IoT tagging module, enabling rich sensor data capture alongside basic DPP access."
    },
    {
      q: "Can we import existing product data?",
      a: "Yes, PhotonicTag offers four robust data import pathways: (1) Manual Entry — Full-featured admin dashboard with form validation, auto-save, and inline guidance for each DPP field. Ideal for initial setup of a few products or for making targeted updates. (2) Excel Bulk Import — Upload .xlsx, .xls, or .csv files up to 10MB. The import engine features intelligent column header mapping that recognizes both English and German field names (e.g., 'Produktname' → Product Name, 'Materialzusammensetzung' → Materials). It handles type conversion, validates required fields, provides a detailed import report showing created/updated/skipped/error counts, and supports email-based deduplication to prevent duplicate records. (3) SAP Bidirectional Sync — Automated data synchronization from SAP S/4HANA (OData API), SAP ECC (RFC/IDoc), or SAP Business One (API). Pre-built field mappings cover standard MARA/MARC structures. Custom field mappings can be configured for Z-tables and customer-specific extensions. Four sync modes: real-time, hourly, daily, and manual. (4) REST API — Full programmatic access via the /api/products endpoint supporting GET, POST, PATCH, DELETE operations. Accepts JSON payloads with Zod schema validation. Suitable for integration with PLM systems, PIM systems, or custom data pipelines."
    },
    {
      q: "What AI capabilities are included?",
      a: "PhotonicTag integrates five AI-powered analysis modules, each generating actionable intelligence from product data: (1) AI Summary — Generates a concise, executive-level overview of the product's DPP data. Useful for quick product reviews and dashboard displays. Highlights key compliance information and sustainability metrics. (2) Sustainability Analysis — Deep environmental impact assessment including carbon footprint estimation based on materials and manufacturing process, water usage analysis, energy consumption profiling, and comparison against industry benchmarks. Provides recommendations for reducing environmental impact. (3) Repair Guide — Assesses repairability based on product design, materials, and construction. Generates step-by-step repair instructions where applicable, identifies common failure modes, lists required tools and spare parts, and estimates repair time and cost. Directly supports the EU Repairability Score requirement. (4) Circularity Score — Assigns a letter grade from A+ to F evaluating the product's circular economy alignment. Considers material recyclability, recycled content percentage, design for disassembly, component reusability, and end-of-life processing requirements. Includes specific recommendations for improving the score. (5) Risk Assessment — Comprehensive compliance gap analysis identifying missing DPP fields, regulatory risks, and potential non-compliance areas. Includes counterfeit risk evaluation based on product characteristics. All AI insights are generated using GPT-4o, cached for performance (subsequent requests for the same product return cached results), and can be refreshed on demand when product data changes."
    },
    {
      q: "Is the platform available as an API for headless integration?",
      a: "Yes, PhotonicTag exposes a comprehensive REST API suitable for headless integration scenarios: Product Management — CRUD operations on /api/products with full DPP schema support. Query filtering, pagination, and search capabilities. Bulk operations supported. IoT Devices — Device registration, sensor data ingestion, and scan tracking via /api/iot-devices. Supports NFC, RFID, and BLE device types. AI Insights — On-demand AI analysis generation via /api/ai/insights/{type}/{productId}. Cached results with force-refresh option. SAP Integration — Sync triggers, conflict detection, and field mapping management via /api/sap/*. Demo Management — Programmatic demo creation and management via /api/internal/demos. Authentication — Session-based authentication with role-based endpoint protection. API consumers authenticate via the team login endpoint and include session cookies in subsequent requests. All endpoints return JSON responses with consistent error formatting (HTTP status codes + error message body). Request validation uses Zod schemas derived from the Drizzle database schema, ensuring type consistency between API contracts and database operations."
    },
    {
      q: "How does the IoT tagging system work?",
      a: "PhotonicTag's IoT module enables smart product tagging beyond traditional QR codes: Supported Technologies — NFC (Near Field Communication) for tap-to-read scanning within 4cm range, RFID (passive UHF) for bulk scanning and warehouse operations at distances up to 10m, and BLE (Bluetooth Low Energy) for continuous proximity monitoring and environmental sensing. Device Lifecycle — Devices are registered in the platform with a unique identifier, device type, firmware version, and linked product. Each device tracks its status (active, inactive, maintenance), battery level (for active tags), and total scan count. Sensor Data — IoT tags can report environmental readings including temperature, humidity, shock/vibration, and light exposure. This data feeds into the product's DPP lifecycle record, enabling condition-based monitoring for sensitive products (pharmaceuticals, food, electronics). Scan Tracking — Every scan event is recorded with timestamp, GPS coordinates (where available), and scan type. This creates a tamper-evident chain of custody record visible in the product's DPP timeline."
    },
    {
      q: "How does PhotonicTag handle data validation and quality?",
      a: "Data quality is critical for regulatory compliance. PhotonicTag enforces quality through multiple layers: Schema Validation — Every product record is validated against the DPP schema using Zod before being persisted. This catches type mismatches, missing required fields, and format violations at the API boundary. Business Rules — Configurable validation rules enforce domain-specific constraints (e.g., carbon footprint values must be positive, recycled content percentages must sum to ≤100%, battery capacity must match chemistry type). Completeness Scoring — Each product receives a DPP completeness percentage showing how many of the required and recommended fields are populated. Products with completeness below a configurable threshold are flagged for attention. AI-Powered Quality Checks — The Risk Assessment AI module identifies potential data inconsistencies, implausible values, and missing critical fields. For example, it can flag a product with 'recycled content: 95%' but 'materials: virgin ABS polymer' as inconsistent. Audit Trail — All data changes are recorded via CloudEvents with timestamps, user identity, and before/after values, enabling root cause analysis for data quality issues."
    },
  ],
  integration: [
    {
      q: "Which SAP systems does PhotonicTag integrate with?",
      a: "PhotonicTag provides certified-grade integration with three SAP product lines: SAP S/4HANA — Connected via OData V4 APIs for real-time, event-driven synchronization. Supports both on-premise and cloud (S/4HANA Cloud) deployments. Reads from and writes to Material Master (MARA/MARC/MARD), Plant Data, and Classification (AUSP/CABN) tables. Supports custom CDS views for extended field access. SAP ECC (ERP Central Component) — Connected via RFC (Remote Function Call) and IDoc (Intermediate Document) interfaces. Supports batch processing for high-volume data exchange. Compatible with SAP ECC 6.0 EHP4 and later. Uses standard BAPIs (BAPI_MATERIAL_GET_ALL, BAPI_MATERIAL_SAVEDATA) for material master operations. SAP Business One — Connected via the Service Layer REST API and DI API. Designed for small-to-midsize enterprises with lighter-weight integration requirements. Supports Items, Business Partners, and Inventory modules. All three integration paths support the same feature set: inbound sync (SAP → PhotonicTag), outbound sync (PhotonicTag → SAP), bidirectional sync with conflict detection, and configurable sync scheduling."
    },
    {
      q: "How does bidirectional sync work with SAP?",
      a: "Bidirectional synchronization is PhotonicTag's most powerful integration capability, designed for organizations that need DPP data to flow seamlessly between their SAP system and the PhotonicTag platform: Inbound Flow (SAP → PhotonicTag) — Material master records are read from SAP via the configured connector (OData/RFC/API). Pre-built field mappings translate SAP structures to DPP fields: MATNR → SKU, MAKTX → Product Name, MTART → Category, MEINS → Unit of Measure, MATKL → Material Group, BRGEW/NTGEW → Weight, and dozens more. Custom mappings can be added for Z-fields and customer extensions. Outbound Flow (PhotonicTag → SAP) — DPP data updates (e.g., sustainability scores, compliance certifications) are pushed back to SAP. This ensures SAP remains the system of record while enriching it with DPP-specific data fields. Conflict Resolution — When the same field has been modified in both systems since the last sync, PhotonicTag detects the conflict and presents a side-by-side comparison. Users can resolve conflicts field-by-field, choosing SAP values, PhotonicTag values, or entering a merged value. Conflict resolution decisions are logged for audit purposes. Sync Monitoring — The SAP Connector dashboard shows sync history, success/failure counts, last sync timestamp, and conflict queue. Failed syncs are automatically retried with exponential backoff."
    },
    {
      q: "What sync frequency options are available?",
      a: "PhotonicTag supports four synchronization modes, configurable per connector: Real-time — Event-triggered synchronization where changes in SAP fire immediate updates to PhotonicTag (and vice versa). Requires webhook or change data capture configuration in SAP. Recommended for: organizations with high data velocity, real-time compliance reporting needs, or just-in-time manufacturing processes. Hourly — Scheduled delta sync running every 60 minutes. Only changed records since the last sync are processed, minimizing SAP system load. Recommended for: organizations with moderate data change rates and near-real-time reporting needs. Daily — Scheduled full or delta sync running once per day (configurable time, typically overnight). Recommended for: organizations with batch-oriented data processes, or those wanting to minimize SAP system impact during business hours. Manual — On-demand sync triggered by an administrator from the PhotonicTag dashboard. Useful for: initial data loads, testing and validation, ad-hoc updates after major data changes. Each mode can be configured independently for inbound vs. outbound direction. For example, you might run real-time inbound sync (SAP changes immediately reflected in DPPs) with daily outbound sync (DPP enrichments pushed to SAP overnight)."
    },
    {
      q: "Can we integrate with non-SAP ERP systems?",
      a: "Yes, PhotonicTag supports integration with non-SAP systems through multiple approaches: REST API — Our comprehensive API (GET/POST/PATCH/DELETE on /api/products) accepts JSON payloads validated against the DPP schema. Any system capable of making HTTP requests can push and pull product data. This works well for Oracle ERP Cloud, Microsoft Dynamics 365, Infor, IFS, and others. Excel Import/Export — The bulk import feature accepts standard Excel files (.xlsx/.xls/.csv) with intelligent column mapping. This provides a low-friction integration path for systems that can export to Excel. Middleware Platforms — PhotonicTag's API works seamlessly with integration middleware like MuleSoft, Boomi, Informatica, and Talend. These tools can orchestrate complex data flows between PhotonicTag and multiple enterprise systems. Custom Connectors — For Enterprise tier customers, we develop custom ERP connectors with pre-built field mappings specific to your ERP's data model. Current roadmap includes native connectors for Oracle ERP Cloud and Microsoft Dynamics 365 F&O. Webhook Notifications — PhotonicTag can emit webhook events when product data changes, enabling event-driven integration architectures with any downstream system."
    },
    {
      q: "How is field mapping configured between SAP and PhotonicTag?",
      a: "Field mapping is the heart of the SAP integration and is fully configurable through the admin dashboard: Pre-Built Mappings — PhotonicTag ships with 30+ pre-configured field mappings covering standard SAP material master fields. These include: MATNR → SKU, MAKTX → Product Name, MTART → Material Type/Category, MEINS → Base Unit of Measure, BRGEW → Gross Weight, NTGEW → Net Weight, GEWEI → Weight Unit, MATKL → Material Group, BISMT → Old Material Number, LABOR → Lab/Design Office, PRDHA → Product Hierarchy, MAGRV → Material Group Packaging, and many more from MARA, MARC, MARD, and MAKT tables. Custom Mappings — You can add mappings for organization-specific SAP extensions (Z-tables, customer fields). The mapping interface supports: simple 1:1 field mapping, concatenation (combining multiple SAP fields into one DPP field), transformation rules (e.g., unit conversion, value mapping), conditional mapping (apply different rules based on material type), and default values for unmapped DPP fields. Validation — Each mapping includes optional validation rules: required field checks, format validation (regex), value range checks, and referential integrity validation. Template Export — Mapping configurations can be exported and imported as JSON, enabling reuse across multiple SAP client systems or environments (DEV → QAS → PRD)."
    },
    {
      q: "What data is exchanged during SAP synchronization?",
      a: "During a sync operation, the following data flows occur: Inbound (SAP → PhotonicTag) — Material master header data (MARA), material descriptions (MAKT in multiple languages), plant-level data (MARC), storage location data (MARD), classification data (AUSP/CABN for characteristics and classes), batch data (MCH1/MCHA), and optionally bill-of-material (STKO/STPO). PhotonicTag maps this data into DPP categories: identification, materials, environmental impact, and compliance. Outbound (PhotonicTag → SAP) — DPP enrichment data including AI-generated sustainability scores, circularity grades, compliance status flags, and QR code URLs. This data is written back to SAP using custom characteristics, Z-fields, or long text objects depending on customer configuration. Data Volume — A typical sync processes 100-10,000 material records per batch. Each record includes 30-50 mapped fields plus metadata. The system uses delta detection (change timestamps) to minimize data transfer volume on subsequent syncs."
    },
    {
      q: "How do you handle SAP transport and landscape management?",
      a: "Enterprise SAP environments typically have a three-system landscape (Development → Quality/Test → Production). PhotonicTag supports this through: Environment Configuration — Each PhotonicTag installation can maintain separate SAP connector configurations for DEV, QAS, and PRD systems. Connection credentials, endpoints, and sync settings are environment-specific. Configuration Transport — Mapping configurations can be exported from one environment and imported into another, mirroring SAP's transport system. This ensures consistency across your landscape. Testing Support — The PhotonicTag demo system can be connected to SAP sandbox or development systems for integration testing without affecting production data. Production Safeguards — Production SAP connectors include additional protections: confirmation dialogs for outbound sync operations, rate limiting to prevent SAP system overload, and comprehensive error logging for SAP basis team review."
    },
  ],
  security: [
    {
      q: "How is user authentication handled?",
      a: "PhotonicTag implements a three-tier authentication architecture designed for enterprise security requirements: Tier 1 — Super Admin (OAuth 2.0 / OpenID Connect): Platform administrators authenticate via Replit's OAuth 2.0 / OIDC provider. This provides the highest security level with token-based authentication, automatic token refresh, and no password storage. Super admins have full access to all platform features including CRM, Demo Factory, User Management, Support Triage, Platform Ops, and all product management functions. Tier 2 — Internal Team (Secure Password Authentication): Sales partners, resellers, and consultants authenticate via email/password. Passwords are hashed using bcrypt with a cost factor of 10 (approximately 100ms per hash operation, making brute-force attacks computationally expensive). Each team member is assigned a specific role (sales_partner, reseller, consultant, demo_viewer) that determines their navigation access and feature permissions. Tier 3 — Demo Viewers (Demo-Specific Credentials): Demo viewers authenticate using per-demo credentials set in the Demo Factory. These credentials provide read-only access to a specific demo's product dashboard, IoT devices, and SAP integration views. Session Management — All sessions are stored server-side in PostgreSQL using connect-pg-simple, with encrypted session cookies (HttpOnly, Secure, SameSite=Lax). Sessions expire after a configurable timeout period. Concurrent session limits prevent unauthorized sharing of credentials."
    },
    {
      q: "Is the platform GDPR compliant?",
      a: "Yes, PhotonicTag is built with GDPR compliance (Regulation (EU) 2016/679) as a foundational design principle, not an afterthought: Data Minimization (Art. 5(1)(c)) — We collect and process only the personal data strictly necessary for platform operation. Product data (which constitutes the majority of stored information) is not personal data under GDPR. Lawful Basis (Art. 6) — User authentication data is processed under 'legitimate interest' (Art. 6(1)(f)) for platform security. Customer CRM data is processed under 'contract performance' (Art. 6(1)(b)). Data Storage (Art. 44-49) — All data is stored in EU-region PostgreSQL databases. No personal data is transferred outside the European Economic Area. Sub-processors (e.g., OpenAI for AI insights) are covered by Standard Contractual Clauses. Security Measures (Art. 32) — Password hashing with bcrypt (cost factor 10), encrypted session storage, role-based access control, CloudEvents audit logging of all data access and modifications. Data Subject Rights (Art. 15-22) — The platform supports data export (Art. 20 - Right to Portability) and data deletion requests (Art. 17 - Right to Erasure). Account administrators can export all account data in JSON format and request complete account deletion. Data Processing Agreement — Enterprise customers receive a comprehensive DPA covering all GDPR processor obligations, including breach notification procedures (Art. 33-34, within 72 hours), sub-processor management, and data retention policies. Records of Processing — The CloudEvents audit trail serves as the Article 30 record of processing activities."
    },
    {
      q: "How is product data protected against tampering?",
      a: "Product data integrity is critical for DPP credibility and is ensured through six layers of protection: (1) Physics-Rooted Identity — PhotonicTag's core technology creates product identity signatures grounded in physical properties that cannot be replicated, forged, or transferred. This goes beyond simple QR codes to create a tamper-proof link between the physical product and its digital passport. (2) CloudEvents Audit Trail — Every data change is recorded as an immutable CloudEvents-compliant event with: timestamp (ISO 8601), user identity (who made the change), event type (create/update/delete), source system (admin UI, SAP sync, API), and before/after field values. This creates a forensic-grade chain of custody for all DPP data. (3) Role-Based Access Control — Three-tier permission system ensuring only authorized users can modify product data. Demo viewers have read-only access. Internal team members can create and edit products but cannot delete or modify audit records. Only super admins have full access. (4) Database-Level Constraints — PostgreSQL enforces data integrity rules at the database level: NOT NULL constraints on required DPP fields, CHECK constraints on value ranges (e.g., percentages must be 0-100), UNIQUE constraints preventing duplicate product identifiers. (5) Input Validation — Every API request is validated against Zod schemas before processing. This prevents injection attacks, type confusion, and malformed data from reaching the database. (6) Session Security — Encrypted session cookies (HttpOnly, Secure flags) prevent session hijacking. Session data is stored server-side in PostgreSQL, not in client-accessible cookies."
    },
    {
      q: "What role-based access levels exist?",
      a: "PhotonicTag implements a comprehensive three-tier role-based access control (RBAC) system: Super Admin — Full platform access including: Product management (create, read, update, delete all products), Internal Operations (CRM with AI health scoring, Demo Factory with credential management, User Management with role assignment, Support Triage with AI categorization, Platform Ops with health monitoring), POC Proposal Generator (multi-language proposal creation with legal terms), SAP Integration management (connector configuration, sync control, conflict resolution), IoT device management, AI insight generation, and system configuration. Internal Team Members — Role-specific access: Sales Partners see CRM dashboards, proposal generation, and Demo Factory. Resellers see CRM and product catalogs. Consultants see CRM, proposals, demos, and product management. All internal team roles can access the product dashboard, product details, IoT device listings, and SAP integration status views. Demo Viewers — Read-only access scoped to their assigned demo: Product dashboard showing demo-specific products, individual product detail pages with DPP data, IoT device listings, and SAP integration demonstration views. Cannot create, edit, or delete any data. Navigation Enforcement — The sidebar navigation dynamically shows/hides menu items based on the authenticated user's role. Protected routes redirect unauthorized users to the appropriate login page."
    },
    {
      q: "How are API keys and secrets managed?",
      a: "PhotonicTag follows security best practices for credential management: Environment-Based Secrets — All sensitive credentials (database connection strings, session secrets, API keys, OAuth client secrets) are stored as encrypted environment secrets, never in source code or configuration files. Zero Hardcoded Credentials — Our CI/CD pipeline includes automated scanning to ensure no credentials are accidentally committed to version control. Runtime Injection — Secrets are injected at runtime through environment variables, following the twelve-factor app methodology. This means credentials can be rotated without code changes or redeployment. Principle of Least Privilege — Each service component has access only to the specific credentials it needs. The frontend has no access to backend secrets. The AI service has access only to the OpenAI API key, not to database credentials. Session Secret Rotation — Session secrets can be rotated without invalidating existing sessions by configuring a secret rotation window. OpenAI API Key Management — The platform uses Replit's AI Integrations for secure OpenAI API key management, providing automatic key rotation and usage monitoring. Audit Logging — All authentication events (login, logout, failed attempts, session creation/destruction) are logged via the CloudEvents bus for security monitoring and incident response."
    },
    {
      q: "What compliance certifications does PhotonicTag support?",
      a: "PhotonicTag's architecture is designed to support and facilitate the following compliance frameworks: SOC 2 Type II — The platform's architecture follows SOC 2 trust service criteria: Security (access controls, encryption, network protection), Availability (health monitoring, auto-recovery), Processing Integrity (input validation, audit trails), Confidentiality (data encryption, access controls), and Privacy (GDPR compliance, data minimization). ISO 27001 — Information security management controls are embedded in the platform design: risk assessment framework, access control policy enforcement, cryptographic controls, and operational security monitoring. GDPR — Full compliance with EU General Data Protection Regulation as detailed in the GDPR FAQ above. EU DPP Regulations — Direct compliance with ESPR (2024/1781), EU Battery Regulation (2023/1542), and upcoming delegated acts for specific product categories. CE Marking — The platform's DPP schema includes fields for CE marking declarations, supporting manufacturers' conformity assessment obligations under Regulation (EU) 2019/1020."
    },
  ],
  pricing: [
    {
      q: "What pricing tiers are available?",
      a: "PhotonicTag offers four carefully structured tiers designed to match organizations at different stages of DPP adoption: POC Tier (€499/month) — Up to 50 products, full DPP creation with all seven ESPR-required data categories, QR code generation and public scan pages, basic product dashboard, manual data entry, limited support. Ideal for proof-of-concept validation and initial evaluation. Starter Tier (€1,499/month) — Up to 1,000 products, everything in POC plus: Excel bulk import with intelligent column mapping, enhanced analytics dashboard, team collaboration with up to 5 users, email support with 48-hour response SLA, basic API access (1,000 requests/day). Ideal for small-to-medium manufacturers starting their DPP journey. Growth Tier (€2,999/month) — Up to 10,000 products, everything in Starter plus: AI-powered insights (sustainability analysis, circularity scoring, repair guides, risk assessment), IoT device integration (NFC/RFID/BLE), advanced analytics and reporting, team management with up to 20 users, priority email support with 24-hour response SLA, full API access (10,000 requests/day). Ideal for mid-market manufacturers with multi-product portfolios. Enterprise Tier (custom pricing) — Unlimited products, everything in Growth plus: SAP S/4HANA/ECC/Business One integration, dedicated account manager, custom SLAs (99.9% uptime guarantee), SSO/SAML authentication, custom branding and white-labeling, unlimited users, phone support with 4-hour response SLA, unlimited API access, POC validation support, custom connector development. Annual billing discount: 20% across all paid tiers. All prices exclude applicable VAT."
    },
    {
      q: "Is there a trial or evaluation period?",
      a: "Yes, PhotonicTag offers a structured evaluation path: POC Tier (€499/month) — The POC tier provides up to 50 products with full DPP creation capabilities, QR code generation, and public scan pages. It is designed for proof-of-concept validation, letting you evaluate the platform with real data before scaling. POC Validation Engagement — For enterprise customers evaluating SAP integration, AI capabilities, and high-volume product management, we offer a structured 4-6 week Proof of Concept engagement with a dedicated project lead, SAP connector configuration, data migration support, and a formal validation report with go/no-go recommendation. POC pricing is applied as credit toward the first year's subscription if you proceed to a higher tier. Risk-Free Evaluation — The POC tier includes milestone-based billing with pro-rated refund if terminated early, minimizing your risk while giving you full platform access to validate the solution for your needs."
    },
    {
      q: "What is included in the Enterprise tier?",
      a: "The Enterprise tier is PhotonicTag's most comprehensive offering, designed for large organizations with complex compliance requirements: Unlimited Products — No cap on the number of products, DPPs, or QR codes. Suitable for organizations with tens of thousands of SKUs across multiple product lines and geographies. SAP Integration Suite — Full bidirectional sync with SAP S/4HANA (OData API), SAP ECC (RFC/IDoc), and SAP Business One (Service Layer). Includes pre-built field mappings, conflict detection and resolution, configurable sync scheduling, and dedicated integration support. AI Intelligence Package — All five AI modules (Summary, Sustainability Analysis, Repair Guide, Circularity Score, Risk Assessment) with priority processing, custom model tuning, and unlimited AI insight generation. IoT Full Suite — Unlimited IoT device registration, sensor data ingestion, real-time monitoring dashboards, and scan analytics. Supports NFC, RFID, and BLE technologies. Dedicated Account Manager — Named account manager for strategic guidance, quarterly business reviews, and escalation path for critical issues. Enterprise SLAs — 99.9% uptime guarantee, 4-hour response time for critical issues, 24/7 monitoring, and disaster recovery with RPO < 1 hour. SSO/SAML — Single Sign-On integration with your existing identity provider (Azure AD, Okta, Auth0, Google Workspace). Custom Branding — White-label the consumer-facing scan pages with your company logo, brand colors, and custom domain. Unlimited Users — No per-user fees. Add as many team members as needed with granular role-based permissions. Custom Development — Access to PhotonicTag's engineering team for custom connector development, API extensions, and integration with your specific enterprise architecture. Compliance Advisory — Access to our regulatory compliance team for guidance on ESPR delegated acts, industry-specific DPP requirements, and audit preparation."
    },
    {
      q: "How does PhotonicTag compare to building DPP compliance in-house?",
      a: "We regularly see organizations evaluate build-vs-buy for DPP compliance. Here's a detailed comparison based on our experience with 50+ enterprise evaluations: In-House Development — Initial Build: 6-12 months with a dedicated team of 3-5 developers (full-stack, database, SAP integration, AI/ML). Estimated cost: €300K-€800K in development resources alone. Ongoing Maintenance: 1-2 FTEs permanently allocated for regulatory updates, security patches, SAP compatibility updates, and feature development. Estimated cost: €150K-€300K/year. Hidden Costs: Legal review of DPP data schemas against ESPR delegated acts (€20K-€50K per review), SAP integration specialist consulting (€2,000-€3,000/day), security audits and penetration testing (€30K-€60K/year), infrastructure hosting and monitoring (€3K-€10K/month). Risk: Regulatory requirements change frequently as the EU publishes new delegated acts. In-house teams must continuously monitor, interpret, and implement these changes. Falling behind creates compliance gaps. PhotonicTag — Time to Value: 4-8 weeks from kickoff to production DPPs. Cost: Predictable monthly subscription with no hidden costs. Enterprise tier typically costs 10-20% of in-house development over a 3-year period. Continuous Compliance: Our team monitors all EU regulatory publications and updates the platform's DPP schemas automatically. You don't need to interpret delegated acts — we do it for you. SAP Integration: Pre-built, tested, and supported. No need for SAP integration specialists. AI Capabilities: GPT-4o powered analysis included. Building equivalent AI capability in-house would require ML engineering resources and ongoing model management. Total Cost of Ownership (3-year): In-house typically €1.2M-€2.5M vs. PhotonicTag Enterprise €200K-€500K."
    },
    {
      q: "What are the payment terms and billing options?",
      a: "PhotonicTag offers flexible billing designed for enterprise procurement processes: Billing Frequency — Monthly billing (standard) or annual billing with a 20% discount. Enterprise customers can choose quarterly billing with a 10% discount. Payment Methods — Credit card (Visa, Mastercard, AMEX) for Starter and Growth tiers. Wire transfer (SEPA, SWIFT) for Enterprise tier. Purchase orders accepted for Enterprise customers with established credit. Currency — All prices quoted in EUR. USD billing available for non-EU customers. Contract Terms — Starter and Growth: Month-to-month with no minimum commitment (annual billing requires 12-month commitment with 20% discount). Enterprise: 12-month minimum with auto-renewal. Custom multi-year agreements (24/36 months) available with additional discounts. POC Billing — POC engagements are billed based on agreed milestones. If the customer converts to an annual Enterprise subscription, the POC investment is credited toward the first year's subscription fee. Volume Discounts — Organizations deploying PhotonicTag across multiple business units or subsidiaries qualify for volume licensing discounts. Contact our sales team for a custom quote."
    },
    {
      q: "Is there a return on investment (ROI) calculation available?",
      a: "Yes, PhotonicTag provides a detailed ROI framework based on four value drivers: (1) Compliance Cost Avoidance — By achieving DPP compliance before deadlines, you avoid potential fines (€100K+ per violation), product seizures, and market access restrictions. For a company with 1,000 SKUs, the potential penalty exposure is €100M+. PhotonicTag's annual cost represents less than 0.5% of this exposure. (2) Operational Efficiency — Automated SAP synchronization eliminates manual data entry for DPP fields. Based on customer data: manual DPP creation averages 45 minutes per product. With SAP sync, this drops to 5 minutes (review and approval only). For 1,000 products, that's 667 hours saved — equivalent to €50K-€100K in labor costs annually. (3) Revenue Protection — As retailers and B2B customers increasingly require DPP compliance from suppliers, having compliant products protects existing revenue streams and opens new market opportunities. Several major European retailers have announced that they will only stock DPP-compliant products starting 2027. (4) Sustainability Reporting — AI-generated sustainability data (carbon footprint, circularity scores) can be used in ESG reporting (CSRD), reducing the cost of separate sustainability data collection and analysis. Typical Enterprise ROI: 300-500% over 3 years. We provide a customized ROI calculation as part of every POC proposal."
    },
  ],
  operations: [
    {
      q: "How do I create a demo for a prospect?",
      a: "The Demo Factory (accessible from the Internal Operations dashboard) enables rapid demo creation in three ways: Template-Based — Choose from 6 pre-built industry templates: Battery (EV and industrial batteries with full battery passport data), Fashion (textiles with fiber composition and microplastic data), Electronics (consumer electronics with repairability scores and spare parts), EV Components (automotive parts with supply chain traceability), Packaging (industrial packaging with recyclability and biodegradability data), and Furniture (furniture with material composition and disassembly guides). Each template generates 3-5 realistic products with complete DPP data. Custom AI-Generated — Write a custom prompt describing the products you want. The AI generates realistic product data including materials, sustainability metrics, and compliance information tailored to your prospect's industry. Combined Approach — Start with a template and customize the generated products through the admin dashboard. Demo Credentials — Each demo can have unique login credentials (email/password) set via the demo settings dialog. Share the demo URL and credentials directly with your prospect. Credential Display — Demo credentials are displayed inline in the Demo Factory with copy buttons for easy sharing. Demo Lifecycle — Demos can be created, customized, and deleted as needed. Product data within demos is fully independent from production data."
    },
    {
      q: "Can I import leads and accounts from Excel?",
      a: "Yes, the CRM module supports comprehensive Excel import with intelligent data mapping: Supported Formats — .xlsx (Excel 2007+), .xls (legacy Excel), and .csv (comma-separated values). Maximum file size: 10MB (approximately 50,000 rows). Intelligent Column Mapping — The import engine automatically recognizes column headers in multiple languages. English mappings: Company Name, Contact Name, Email, Phone, Industry, Status, etc. German mappings: Firma/Unternehmen → Company Name, Vorname → First Name, Nachname → Last Name, E-Mail → Email, Telefon → Phone, Branche → Industry, etc. Import Modes — Import as Leads (for sales pipeline tracking with conversion metrics) or as Customer Accounts (for CRM account management with health scoring). Deduplication — Email-based deduplication prevents duplicate records. When a matching email is found, the system updates the existing record with new data rather than creating a duplicate. Import Report — After import, a detailed report shows: total rows processed, records created (new), records updated (existing matches), records skipped (validation failures), specific error messages for each failed row, and column mapping applied. Validation — Required fields are enforced during import. Invalid email formats, missing company names, and other data quality issues are reported with row numbers for easy correction."
    },
    {
      q: "How does AI health scoring work in the CRM?",
      a: "PhotonicTag's AI-driven Customer Health Scoring analyzes multiple signals to produce a 0-100 health score for each account: Input Signals — The AI considers: Monthly Recurring Revenue (MRR) trend (growing/stable/declining), product usage metrics (active products, API calls, scan volume), engagement patterns (last login, support ticket frequency, feature adoption), contract status (renewal date proximity, commitment level), and activity history (meetings, emails, product updates). Score Ranges — 80-100 (Healthy): Strong engagement, growing usage, low churn risk. 50-79 (Moderate): Some engagement gaps or declining trends that need attention. 20-49 (At Risk): Significant decline in usage or engagement, proactive intervention recommended. 0-19 (Critical): Minimal activity, high churn probability, immediate action required. AI Next-Best-Actions — For each account, the AI generates prioritized action recommendations: schedule a check-in call, propose an upsell to a higher tier, offer training on underutilized features, escalate to account management, send usage tips, or initiate renewal discussion. Each action includes a reasoning explanation and priority level. Dashboard Visibility — The CRM dashboard prominently displays at-risk accounts, pending actions, total MRR, and average health score. Actions can be completed or dismissed directly from the dashboard."
    },
    {
      q: "How do I generate a POC proposal for a customer?",
      a: "The Proposals tab in the Internal Operations dashboard provides a full-featured POC Proposal Generator: Language Selection — Choose from English, German (Deutsch), French (Français), or Spanish (Español). The entire proposal — including all legal terms, scope descriptions, and deliverables — is generated in the selected language. Customer Details — Enter the customer/company name, industry, contact person, and contact email. This information is woven into the proposal text. Project Scope — Define the product scope (e.g., 'EV batteries and industrial cells'), estimated product volume (e.g., '500-1000 SKUs'), SAP system type (S/4HANA, ECC, Business One, or none), and desired timeline. Pricing Tier — Select the appropriate tier (POC, Starter, Growth, Enterprise) to auto-populate pricing information. Generated Document — The proposal is exported as an editable Microsoft Word (.docx) file containing: Executive Summary, Scope of Work, Technical Architecture, SAP Integration details, Timeline & Milestones (6-week plan), Deliverables, Commercial Terms (with tier-specific pricing), Legal Terms & Conditions (8 comprehensive clauses including confidentiality, GDPR/DPA, IP rights, liability, termination, governing law, force majeure, and warranty), Next Steps, and dual Signature Pages. The Word document is fully editable — sales consultants can customize any section before sending to the customer."
    },
    {
      q: "What support channels are available?",
      a: "PhotonicTag provides tiered support aligned with your subscription: POC Tier — Community documentation, FAQs, and public knowledge base. Self-service product documentation with 9 comprehensive sections. Email support for onboarding questions. Starter Tier — Email support (support@photonictag.com) with 48-hour response SLA. Access to the internal knowledge base with troubleshooting guides. Growth Tier — Priority email support with 24-hour response SLA. Quarterly product training webinars. Access to the API support channel for integration questions. Enterprise Tier — Dedicated account manager for strategic guidance and escalation. Phone support with 4-hour response SLA for critical issues. 24/7 monitoring with proactive alerting. Quarterly business reviews. Access to the PhotonicTag engineering team for custom integration support. For all tiers, the AI Support Triage system automatically categorizes incoming tickets by type (bug, feature request, compliance question, integration issue), assigns priority levels, generates tags for efficient routing, and creates AI summaries for faster resolution by the support team."
    },
    {
      q: "How do I monitor platform health?",
      a: "The Platform Ops tab provides comprehensive real-time system monitoring: Uptime Monitoring — Current uptime percentage displayed prominently, with historical uptime data. The system targets 99.9% uptime for Enterprise customers, with automatic health check probes running every 30 seconds. Resource Utilization — Real-time memory usage (heap used vs. total heap, RSS), process uptime, and Node.js version. These metrics help identify performance degradation before it impacts users. Entity Counts — Live counts of all database entities: products, IoT devices, AI insights, support tickets, customer accounts, demo configurations, partners, leads, and internal users. These counts update automatically and provide a quick pulse check on platform activity. Auto-Refresh — The dashboard refreshes every 30 seconds automatically, providing near-real-time visibility without manual page reloads. System Information — Node.js version, platform details, and deployment environment information for troubleshooting and support ticket context."
    },
    {
      q: "How can I download the presentation for customer meetings?",
      a: "PhotonicTag provides a professional, editable PowerPoint presentation that can be downloaded directly from the Presentation page (/presentation): Download Process — Click the 'Download PPT' button in the hero section. The system generates a 9-slide editable .pptx file and downloads it to your device. Slide Contents — The presentation includes: Title slide (PhotonicTag branding and tagline), The Regulatory Challenge (ESPR compliance timeline), Platform Capabilities (6 core modules), Why PhotonicTag (6 key differentiators), Target Industries & Deadlines (6 industry segments with deadline table), Technical Architecture (platform stack and security features), Internal Operations Platform (CRM, Demo Factory, Support, Ops), Pricing Overview (4-tier comparison), and Call-to-Action (demo scheduling). Fully Editable — The .pptx file is a standard Microsoft PowerPoint file that can be opened in PowerPoint, Google Slides, or Keynote. All text, layouts, colors, and content can be customized for specific customer presentations. Brand Consistent — The presentation uses PhotonicTag's brand colors and professional formatting, suitable for executive-level customer meetings."
    },
  ],
};

export default function FAQs() {
  const [activeCategory, setActiveCategory] = useState<FAQCategory>("compliance");

  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>FAQs - PhotonicTag | EU Digital Product Passport Questions</title>
        <meta name="description" content="Frequently asked questions about PhotonicTag. EU DPP compliance, SAP integration, security, pricing, and technical documentation." />
        <meta property="og:title" content="PhotonicTag - Frequently Asked Questions" />
        <meta property="og:description" content="Common questions about EU Digital Product Passport compliance, SAP integration, and the PhotonicTag platform." />
      </Helmet>
      <PublicNav />

      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-12">
          <Badge variant="secondary" className="mb-3">FAQ</Badge>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-3" data-testid="text-faqs-title">
            Frequently Asked Questions
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Common questions about EU DPP compliance, platform capabilities, SAP integration, security, and operations.
          </p>
        </div>

        <div className="flex flex-wrap gap-2 justify-center mb-10">
          {faqCategories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                activeCategory === cat.id
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-muted-foreground hover:text-foreground hover:bg-muted/80"
              }`}
              data-testid={`button-faq-category-${cat.id}`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        <Accordion type="single" collapsible className="space-y-3">
          {faqs[activeCategory].map((faq, i) => (
            <AccordionItem key={`${activeCategory}-${i}`} value={`${activeCategory}-${i}`} className="border rounded-lg px-4" data-testid={`faq-item-${activeCategory}-${i}`}>
              <AccordionTrigger className="text-left font-medium py-4 hover:no-underline" data-testid={`faq-trigger-${activeCategory}-${i}`}>
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground pb-4 leading-relaxed">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <div className="mt-16 text-center">
          <h2 className="text-2xl font-bold mb-3">Still have questions?</h2>
          <p className="text-muted-foreground mb-6 max-w-lg mx-auto">
            Our team is happy to answer your questions about PhotonicTag, EU DPP compliance, or how we can help your organization.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" asChild data-testid="button-faqs-demo">
              <a href="https://calendar.app.google/Aa9nfUnJiZvcjXi28" target="_blank" rel="noopener noreferrer" className="gap-2">
                <Calendar className="w-4 h-4" />
                Schedule a Demo
              </a>
            </Button>
            <Button size="lg" variant="outline" asChild data-testid="button-faqs-contact">
              <Link href="/contact" className="gap-2">
                <ArrowRight className="w-4 h-4" />
                Contact Sales
              </Link>
            </Button>
          </div>
        </div>
      </main>

      <PublicFooter />
    </div>
  );
}
